// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBxL1RczqOUxjVSov-ymPLgRHq0dUJzi4',
    appId: '1:862870287105:web:752cf4961ae6ba60d8e100',
    messagingSenderId: '862870287105',
    projectId: 'newerclosetswap',
    authDomain: 'newerclosetswap.firebaseapp.com',
    storageBucket: 'newerclosetswap.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDABCPVxR6zbuP2p7UUMyo3GhFjSGyPssU',
    appId: '1:862870287105:android:59f1f673b4a2425fd8e100',
    messagingSenderId: '862870287105',
    projectId: 'newerclosetswap',
    storageBucket: 'newerclosetswap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTcHEjxFKD0LYlVvNf5G8DlTM4rg5gejk',
    appId: '1:862870287105:ios:497b4a6c12305603d8e100',
    messagingSenderId: '862870287105',
    projectId: 'newerclosetswap',
    storageBucket: 'newerclosetswap.appspot.com',
    androidClientId: '862870287105-irq9t26tlsl3kgs45sl50ham1r4f0smr.apps.googleusercontent.com',
    iosClientId: '862870287105-8krvjk86vpfenbffus64gdmqadlqkdsa.apps.googleusercontent.com',
    iosBundleId: 'com.example.betterclosetswap',
  );
}
